#!/usr/bin/env python3
from pathlib import Path
import argparse
import sys
import os

M06-2X_S0_OPT_TEMPLATE = """\
! M06-2X def2-TZVP def2/J RIJCOSX D3BJ TightSCF TightOpt Grid5 FinalGrid6 CPCM({solvent})
%maxcore 1000
%pal nprocs 1 end
%geom
  MaxIter 500
end
* xyzfile {charge} {mult} {xyz}
"""

M062X_S0_FREQ_TEMPLATE = """\
! M06-2X def2-TZVP def2/J RIJCOSX D3BJ TightSCF AnFreq Grid5 FinalGrid6 CPCM({solvent})
%maxcore 1000
%pal nprocs 1 end
* xyzfile {charge} {mult} {xyz}
"""

M062X_T1_OPT_TEMPLATE = """\
! UM06-2X def2-TZVP def2/J RIJCOSX D3BJ TightSCF TightOpt Grid5 FinalGrid6 CPCM({solvent})
%maxcore 1000
%pal nprocs 1 end
%geom
  MaxIter 500
end
* xyzfile {charge} {mult} {xyz}
"""

M062X_T1_FREQ_TEMPLATE = """\
! UM06-2X def2-TZVP def2/J RIJCOSX D3BJ TightSCF AnFreq Grid5 FinalGrid6 CPCM({solvent})
%maxcore 1000
%pal nprocs 1 end
* xyzfile {charge} {mult} {xyz}
"""
# addition of "U" switches to unrestricted SCF for the open-shell triplet.





