#!/usr/bin/env python3

from pathlib import Path
import argparse
import sys
import os

B3LYP_OPT_TEMPLATE = """\
! B3LYP def2-TZVP def2/J RIJCOSX D3BJ TightSCF TightOpt CPCM(solvent) 
%maxcore 1000
%pal nprocs 1 end
* xyzfile {charge} {mult} {xyz}
"""

B3LYP_FREQ_TEMPLATE = """\
! B3LYP def2-TZVP def2/J RIJCOSX D3BJ TightSCF AnFreq CPCM(solvent)
%maxcore 1000
%pal nprocs 16 end
* xyzfile {charge} {mult} {xyz}
"""

CAM-B3LYP_TDDFT_TEMPLATE = """\
! CAM-B3LYP def2-TZVP def2/J RIJCOSX TightSCF CPCM(solvent)
%maxcore 4000
%pal nprocs 8 end
%tddft
  nroots 5
  tda false
  triplets true
  maxdim 5
end
* xyzfile {charge} {mult} {xyz}
"""

WB97X-D3_TDDFT_TEMPLATE = """\
! wB97X-D3 def2-TZVP def2/J RIJCOSX TightSCF CPCM(solvent)
%maxcore 4000
%pal nprocs 8 end
%tddft
  nroots 5
  tda false        # strongly recommended with triplets + range-separated hybrid
  triplets true  # set true only if needed, and use tda true if so
  maxdim 5
end
* xyzfile {charge} {mult} {xyz}
"""

DLPNO-STEOM-CCSD_TEMPLATE = """\
! DLPNO-STEOM-CCSD def2-TZVP def2-TZVP/C RIJCOSX TightSCF
%maxcore 1000
%pal nprocs 1 end

%cpcm
  solvent "solvent"
end

%mdci
  NRoots 1
  NActIP 8
  NActEA 6
  DoCISNat false
  DoRootWise false
  OThresh 0.005
  VThresh 0.005
  TCutPNOSingles 1e-11
  NDAV 400
  MaxIter 300
  DTol 1e-5
  DoSimpleDens false
  AddL2Term true
end
* xyzfile {charge} {mult} {xyz}
"""

RUN_OPT_FREQ_TDDFT_TEMPLATE = """\
#!/bin/bash
opt_jid=$(qorca -i ./{opt_file} -c {cores} -m 2500)
jid=$(qorca -i ./{freq_file} -c {cores} -m 2500 -n 1 -j ${{opt_jid}})
cam-b3lyp_jid=$(qorca -i ./{cam-b3lyp_tddft_file} -c {cores} -m 2500 -j ${{opt_jid}})
wb97x-d3_jid=$(qorca -i ./{wb97x-d3_tddft_file} -c {cores} -m 2500 -j ${{opt_jid}})
"""

RUN_DLPNO-STEOM-CCSD_TEMPLATE = """\
#!/bin/bash
jid=$(qorca -i ./{ccsd_file} -c {cores} -m 8000 -d 6000 -n 1 -j ${{opt_jid}})
"""

def main():
    parser = argparse.ArgumentParser(description="Generate ORCA inputs + run script")
    parser.add_argument("name", help="Input file name")
    parser.add_argument("xyz", help="Input .xyz file")
    parser.add_argument("charge", help="Molecule net charge", type=int)
    parser.add_argument("-c", "--cores", type=int, default=16)
    args = parser.parse_args()

    xyz_path = Path(args.xyz)

    if not xyz_path.exists():
        print(f"Error: {xyz_path} not found.")
        sys.exit(1)

    if xyz_path.suffix != ".xyz":
        print("Error: input must be .xyz")
        sys.exit(1)

    stem = args.name
    mult = 1

    b3lyp_opt_stem = f"{stem}_b3lyp_def2-tzvp_opt"
    b3lyp_opt_file = Path(b3lyp_opt_stem + ".inp")
    b3lyp_opt_xyz_file = Path(b3lyp_opt_stem + ".xyz")
    b3lyp_freq_file = Path(f"{stem}_b3lyp_def2-tzvp_freq.inp")
    cam-b3lyp_tddft_file = Path(f"{stem}_cam-b3lyp_def2-tzvp_tddft.inp")
    wb97x-d3_tddft_file = Path(f"{stem}_wb9x-d3_def2-tzvp_tddft.inp")
    dlpno-steom-ccsd_file = Path(f"{stem}_dlpno_steom_ccsd.inp")
    run_file = Path(f"run_{stem}_opt_freq_tddft.sh")
    dlpno_run_file = Path(f"run_{stem}_dlpno_steom_ccsd.sh")

    b3lyp_opt_file.write_text(B3LYP_OPT_TEMPLATE.format(charge=args.charge, mult=mult, xyz=xyz_path.name))
    b3lyp_freq_file.write_text(B3LYP_FREQ_TEMPLATE.format(charge=args.charge, mult=mult, xyz=b3lyp_opt_xyz_file))
    cam-b3lyp_tddft_file.write_text(CAM-B3LYP_TDDFT_TEMPLATE.format(charge=args.charge, mult=mult, xyz=b3lyp_opt_xyz_file))
    wb97x-d3_tddft_file.write_text(WB97X-D3_TDDFT_TEMPLATE.format(charge=args.charge, mult=mult, xyz=b3lyp_opt_xyz_file))
    run_file.write_text(RUN_TEMPLATE.format(
        opt_file=opt_file,
        freq_file=freq_file,
        cores=args.cores
    ))

    # Make run.sh executable
    os.chmod(run_file, 0o755)

if __name__ == "__main__":
    main()
