#!/usr/bin/env python3

from pathlib import Path
import argparse
import sys
import os

S0_OPT_TEMPLATE = """\
! B3LYP D3BJ cc-pVTZ TightOpt FREQ CPCM({solvent})
%maxcore 1000
%pal nprocs 16 end
* xyzfile {charge} {mult} {xyz}
"""

T1_OPT_TEMPLATE = """\
! B3LYP D3BJ cc-pVTZ TightOpt FREQ CPCM({solvent})
%maxcore 1000
%pal nprocs 16 end
* xyzfile {charge} {mult} {xyz}
"""

CCSD_S0GEOM_TEMPLATE = """\
! DLPNO-CCSD(T) cc-pVDZ cc-pVDZ/C AutoAux NormalPNO TightSCF CPCM({solvent})
%maxcore 7125
%pal nprocs 8 end
* xyzfile {charge} {mult} {xyz}
"""

CCSD_T1GEOM_TEMPLATE = """\
! UHF DLPNO-CCSD(T) cc-pVDZ cc-pVDZ/C AutoAux NormalPNO TightSCF CPCM({solvent})
%maxcore 7125
%pal nprocs 8 end
* xyzfile {charge} {mult} {xyz}
"""

RUN_TEMPLATE = """\
#!/bin/bash
s0_opt_jid=$(qorca -i ./{s0_opt_file} -c {cores} -m 2500)
T1_opt_jid=$(qorca -i ./{t1_opt_file} -c {cores} -m 2500)
s0_ccsd_jid=$(qorca -i ./{ccsd_s0geom_file} -c 8 -m 9500 -d 2000 -n 1 -j ${{s0_opt_jid}})
t1_ccsd_jid=$(qorca -i ./{ccsd_t1geom_file} -c 8 -m 9500 -d 2000 -n 1 -j ${{T1_opt_jid}})
"""

def main():
    parser = argparse.ArgumentParser(description="Generate ORCA inputs + run script")
    parser.add_argument("name", help="Input file name")
    parser.add_argument("xyz", help="Input .xyz file")
    parser.add_argument("charge", help="Molecule net charge", type=int)
    parser.add_argument("-c", "--cores", type=int, default=16)
    parser.add_argument("-s", "--solvent", default="water",
                        help="Solvent name for CPCM (e.g. water, acetonitrile, dichloromethane)")
    args = parser.parse_args()

    xyz_path = Path(args.xyz)

    if not xyz_path.exists():
        print(f"Error: {xyz_path} not found.")
        sys.exit(1)

    if xyz_path.suffix != ".xyz":
        print("Error: input must be .xyz")
        sys.exit(1)

    stem = args.name
    mult3 = 3
    mult1= 1

    s0_opt_stem = f"{stem}_b3lyp_cc-pVDZ_s0_opt"
    s0_opt_file = Path(s0_opt_stem + ".inp")
    s0_opt_xyz_file = Path(s0_opt_stem + ".xyz")
     
    t1_opt_stem = f"{stem}_b3lyp_cc-pVDZ_t1_opt"
    t1_opt_file = Path(t1_opt_stem + ".inp")
    t1_opt_xyz_file = Path(t1_opt_stem + ".xyz")

    ccsd_s0geom_file = Path(f"{stem}_ccsd_s0geom.inp")
    ccsd_t1geom_file = Path(f"{stem}_ccsd_t1geom.inp")
    run_file = Path(f"run_{stem}_campos_t1.sh")
    

    s0_opt_file.write_text(S0_OPT_TEMPLATE.format(charge=args.charge, mult=mult1, xyz=xyz_path.name)) 
    t1_opt_file.write_text(T1_OPT_TEMPLATE.format(charge=args.charge, mult=mult3, xyz=xyz_path.name))
    ccsd_s0geom_file.write_text(CCSD_S0GEOM_TEMPLATE.format(charge=args.charge, mult=mult1, xyz=s0_opt_xyz_file))
    ccsd_t1geom_file.write_text(CCSD_T1GEOM_TEMPLATE.format(charge=args.charge, mult=mult3, xyz=t1_opt_xyz_file))
    run_file.write_text(RUN_TEMPLATE.format(
        s0_opt_file=s0_opt_file,
        t1_opt_file=t1_opt_file,
        ccsd_s0geom_file=ccsd_s0geom_file,
        ccsd_t1geom_file=ccsd_t1geom_file,
        cores=args.cores
    ))

    # Make run.sh executable
    os.chmod(run_file, 0o755)

if __name__ == "__main__":
    main()
